Vagrant.configure("2") do |config|
  config.vm.box = "almalinux/9"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.provider "libvirt" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.provision "shell", path: "./all-in-one.sh"
end
