Vagrant.configure("2") do |config|
  config.vm.box = "almalinux/9"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.provider "libvirt" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.provision "shell", path: "./01-before-reboot.sh"
  config.vm.provision "shell", reboot: true
  config.vm.provision "shell", path: "./02-after-reboot.sh"
end
